apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-uninstall
spec:
  workspaces:
    - name: install-dir
      mountPath: "/tekton/home/"
  params:
    - name: OPENSHIFT_INSTALLER_IMAGE
      type: string
      description: OpenShift installer base image for UPI installation
      default: docker.io/praveen4g0/release-tests-bootstrap-image:v0.0.2
  steps:
    - name: remove-cluster
      image: $(params.OPENSHIFT_INSTALLER_IMAGE)
      workingDir: $(workspaces.install-dir.path)
      script: |
        #!/usr/bin/env bash
        echo "Trying to delete the cluster"
        timeout 30m /usr/local/bin/openshift-install destroy cluster --log-level=debug || true
      securityContext:
        runAsUser: 0